### ISSUE TITLE
Does not work with Jenkins 2.387.1

### ISSUE THREAD

**Issue by kico-itexto** [jenkinsci/zulip-plugin#37]
### Jenkins and plugins versions report

<details>
Jenkins 2.387.1
Zulip Plugin 1.3.0
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux - Ubuntu 20.04

### Reproduction steps

When trying to send any message with the plugin we'll get the error 

`
Error when executing failure post condition:
java.lang.ClassNotFoundException: org.apache.commons.httpclient.Credentials
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at jenkins.util.URLClassLoader2.findClass(URLClassLoader2.java:35)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
Caused: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/Credentials
	at jenkins.plugins.zulip.ZulipSendStep.perform(ZulipSendStep.java:44)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

### Expected Results

This should work, the message should be sent

### Actual Results

The exception is thrown

### Anything else?

Probably related to this issue: https://github.com/jenkinsci/zulip-plugin/pull/36

**Comment by butchyyyy** [comment]
Duplicate of #35
